List<String> users = [
  "ali",
  'Behnam',
  'Mohammad',
  "Sara",
  "Group Friends",
  "Mojgan",
  "Rabert",
  "Zahra",
  "Fatemeh",
  "Javad",
  "Jigar"
  "ali",
  'Behnam',
  'Mohammad',
  "Sara",
  "Group Friends",
  "Mojgan",
  "Rabert",
  "Zahra",
  "Fatemeh",
  "Javad",
  "Jigar"
];

List<String> type = [
  "Hello. How are you?",
  "ohhh! Noooooo!!!",
  "thanks. im very hungery. tomorrow, don't eat any food!",
  "really?! no it's very bad. really sorry.",
  "Hello. How are you?",
  "ohhh! Noooooo!!!",
  "thanks. im very hungery. tomorrow, don't eat any food!",
  "really?! no it's very bad. really sorry.",
  "Hello. How are you?",
  "ohhh! Noooooo!!!",
  "thanks. im very hungery. tomorrow, don't eat any food!",
  "Hello. How are you?",
  "ohhh! Noooooo!!!",
  "thanks. im very hungery. tomorrow, don't eat any food!",
  "really?! no it's very bad. really sorry.",
  "Hello. How are you?",
  "ohhh! Noooooo!!!",
  "thanks. im very hungery. tomorrow, don't eat any food!",
  "really?! no it's very bad. really sorry.",
  "Hello. How are you?",
  "ohhh! Noooooo!!!",
  "thanks. im very hungery. tomorrow, don't eat any food!",
];

